# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10, verbose_name='Número de cuenta')),
                ('installment_value', models.FloatField(verbose_name='Valor de la cuota')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Manager', verbose_name='Aprobado por')),
            ],
        ),
    ]
