# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0002_creditrequest'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.CreditRequest', verbose_name='Solicitud'),
        ),
    ]
