# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_creditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='installments',
            field=models.IntegerField(choices=[(6, 6), (12, 12), (24, 24), (36, 36)], default=6, max_length=2, verbose_name='Cuotas'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creada'), (1, 'Evaluada'), (2, 'Aprobada'), (3, 'Rechazada')], default=0, max_length=2, verbose_name='Estado'),
        ),
    ]
